version: '3.8'
services:
  mongo:
    image: mirror.gcr.io/library/mongo:8
    platform: linux/amd64
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_user
      MONGO_INITDB_ROOT_PASSWORD: web3
    ports:
      - "27017:27017"
    networks:
      - mongo-network

  calculadora:
    image: ghcr.io/ricardoesq/desarrollowebiii:latest-backend
    pull_policy: always
    platform: linux/amd64
    ports:
      - "8000:8000"
    networks:
      - mongo-network
    depends_on:
      - mongo

  frontend:
    image: ghcr.io/ricardoesq/desarrollowebiii:latest-frontend
    platform: linux/amd64
    ports:
      - "3000:3000"
    depends_on:
      - calculadora
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
