version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: web-frontend
    ports:
      - "5173:5173"
    networks:
      - monitoring-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api-backend
    ports:
      - "8000:8000"
    networks:
      - monitoring-net

  mariadb:
    image: mariadb:10.6
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - monitoring-net

networks:
  monitoring-net:

volumes:
  mariadb_data:
