name: Build and Push Frontend Docker Image

on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"
    paths:
      - "frontend-app/**"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine image tags (Latest / Version)
        id: vars
        run: |
          # Convertir el nombre del repositorio a minúsculas
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_NAME=${REPO_LOWER}" >> $GITHUB_ENV

          # Determinar tag (latest o versión)
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          else
            echo "TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build Docker image for Frontend
        run: |
          docker build -f ./frontend-app/Dockerfile -t ghcr.io/${{ env.REPO_NAME }}:${{ env.TAG }}-frontend ./frontend-app

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ env.REPO_NAME }}:${{ env.TAG }}-frontend
